branches:
  only:
  - master
  - devel

env:
  global:
  - RGL_USE_NULL=TRUE
  - PKG_CFLAGS="-O3 -Wall -pedantic"

language: R
sudo: required
cache: packages

cran: http://cran.rstudio.com
warnings_are_errors: true
r_build_args: "--no-manual"
r_check_args: "--no-build-vignettes --no-manual"

r:
  - release
  - devel

addons:
  apt:
    - sources:
      - deadsnakes

before_install:
  - sudo apt-get -y install libx11-dev mesa-common-dev libglu1-mesa-dev
  - sudo apt-get -y install python3.6 python3.6-dev
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - python3.6 -m pip install --upgrade pip setuptools
  - python3.6 -m pip install --quiet --ignore-installed numpy tensorflow keras
  - sudo $(which R) CMD javareconf

r_packages:
  - devtools
  - covr
  - sessioninfo
  - data.table
  - Rdpack
  - delayed
  - hal9001
  - haldensify

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo
  - tlverse/origami

after_success:
  - travis_wait 80 Rscript -e 'covr::codecov()'
  - Rscript -e "devtools::test_file('$TRAVIS_BUILD_DIR/tests/testthat/test-keras.R')" 

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
